import { IUserMock } from "../types";

export let usersAllInfo: IUserMock[] = [
    {
        id: 1,
        name: "Homebrewer_27",
        email: "Homebrewer_27@example.com",
        image: "/images/avatars/avatar1.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [],
    },
    {
        id: 2,
        name: "Homebr",
        email: "Homebr@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 3,
        name: "r_27",
        email: "r_27@example.com",
        image: "/images/avatars/avatar2.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 4,
        name: "UKAleMaster",
        email: "UKAleMaster@example.com",
        image: "/images/avatars/avatar2.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 5,
        name: "MashAndSparge",
        email: "MashAndSparge7@example.com",
        image: "/images/avatars/avatar3.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 6,
        name: "CraftyBrewer_USA",
        email: "CraftyBrewer_USA@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 7,
        name: "Fermentation_Fred",
        email: "Fermentation_Fred@example.com",
        image: "/images/avatars/avatar5.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 8,
        name: "HopHead_Jessie",
        email: "HopHead_Jessie@example.com",
        image: "/images/avatars/avatar6.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 9,
        name: "NewbieBrewer_Mark",
        email: "NewbieBrewer_Mark@example.com",
        image: "/images/avatars/avatar7.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 10,
        name: "PaleAlePete",
        email: "PaleAlePete@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 11,
        name: "AromaAddict",
        email: "AromaAddict@example.com",
        image: "/images/avatars/avatar9.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 12,
        name: "BrewAnalyst",
        email: "BrewAnalyst@example.com",
        image: "/images/avatars/avatar10.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 13,
        name: "AmberAleFanatic",
        email: "AmberAleFanatic@example.com",
        image: "/images/avatars/avatar1.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 14,
        name: "BrewMore",
        email: "BrewMore@example.com",
        image: "/images/avatars/avatar2.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 15,
        name: "ConsistentBrewer",
        email: "ConsistentBrewer@example.com",
        image: "/images/avatars/avatar3.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 16,
        name: "PilsnerPurist",
        email: "PilsnerPurist@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 17,
        name: "BelgianBrewer",
        email: "BelgianBrewer@example.com",
        image: "/images/avatars/avatar5.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 18,
        name: "PracticalBrewer",
        email: "PracticalBrewer@example.com",
        image: "/images/avatars/avatar6.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 19,
        name: "LagerLover",
        email: "LagerLover@example.com",
        image: "/images/avatars/avatar7.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    }, 
    {
        id: 20,
        name: "TheMaltster",
        email: "TheMaltster@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 21,
        name: "HomebrewHobbyist",
        email: "HomebrewHobbyist@example.com",
        image: "/images/avatars/avatar9.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    }, 
    {
        id: 22,
        name: "HouseStrainGuy",
        email: "HouseStrainGuy@example.com",
        image: "/images/avatars/avatar10.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 23,
        name: "IPA_Fan",
        email: "IPA_Fan@example.com",
        image: "/images/icons/User_alt.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 24,
        name: "TempControlFreak",
        email: "TempControlFreak@example.com",
        image: "/images/avatars/avatar2.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 25,
        name: "IPA_Fan",
        email: "IPA_Fan@example.com",
        image: "/images/avatars/avatar3.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 26,
        name: "BitterIsBetter",
        email: "BitterIsBetter@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 27,
        name: "WestCoastBrewer",
        email: "WestCoastBrewer@example.com",
        image: "/images/avatars/avatar5.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 28,
        name: "BelgianBeerGeek",
        email: "BelgianBeerGeek@example.com",
        image: "/images/avatars/avatar2.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 29,
        name: "MashMaster_Pro",
        email: "MashMaster_Pro@example.com",
        image: "/images/avatars/avatar3.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 30,
        name: "PatientBrewer",
        email: "PatientBrewer@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 31,
        name: "HazyHead",
        email: "HazyHead@example.com",
        image: "/images/avatars/avatar6.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 32,
        name: "FlavorExplorer",
        email: "FlavorExplorer@example.com",
        image: "/images/avatars/avatar7.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 33,
        name: "DIPA_Dan",
        email: "DIPA_Dan@example.com",
        image: "/images/avatars/avatar4.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 34,
        name: "IPA_Lover_82",
        email: "IPA_Lover_82@example.com",
        image: "/images/avatars/avatar9.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 35,
        name: "FrugalBrewer",
        email: "FrugalBrewer@example.com",
        image: "/images/avatars/avatar10.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 36,
        name: "SweetToothHomebrew",
        email: "SweetToothHomebrew@example.com",
        image: "/images/avatars/avatar1.svg",
        phone: '',
        city: '',    
        address: '',
        orders: [], 
    },
    {
        id: 37,
        name: "Елена Вишняк",
        email: "vishnyak-elena@mail.ru",
        image: '',
        phone: '',
        city: '',    
        address: '',
        orders: [], 
        role: 'admin',
    },
]

export function ensureGitHubUserExists(githubUser: { name: string; email: string; image?: string | null }) {
    const exists = usersAllInfo.find(u => u.email === githubUser.email);
    
    if (!exists) {
        const newUser: IUserMock = {
            id: usersAllInfo.length + 1,
            name: githubUser.name || "GitHub User",
            email: githubUser.email,
            image: githubUser.image || "/public/images/icons/User_alt.svg",
            phone: "",    
            city: "",     
            address: "",
            orders: [] 
        };
        
        usersAllInfo.push(newUser);
        console.log(`[UsersDB] Зарегистрирован новый пользователь. Аватар: ${newUser.image}`);
    }
}